### ISSUE TITLE
TO-DO before merging wip/clean

### ISSUE THREAD

**Issue by gmscs** [RicinApp/Ricin#42]
- [ ] Fix ToxID not appearing on the settings-view
- [ ] Fix settings-view combo-boxes not being populated
- [ ] Fix theme being broken for several system themes (settings on Numix; text on Raleigh; tab-text on most themes...)
- [ ] Fix name/status text selection (top-left) with theme
- [ ] Make System Themes & System Icons an option
- [ ] Be able to select more that one message in the chat view.
- [ ] White theme

Please keep adding as stuff appears.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/30603081-to-do-before-merging-wip-clean?utm_campaign=plugin&utm_content=tracker%2F24002221&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F24002221&utm_medium=issues&utm_source=github).
</bountysource-plugin

**Comment by benwaffle** [comment]
What is in that branch?

**Comment by gmscs** [comment]
This branch contains the **theme updates** (black); the **sidepane updates**; and several important **bugfixes.**

**Comment by SkyzohKey** [comment]
I'm working on a **white** version of the theme. :)
![](http://i.imgur.com/uxeDl6y.png)

**Comment by SkyzohKey** [comment]
This issue is now closed, I opened a PR to continue working on efficiently. https://github.com/RicinApp/Ricin/pull/43
